### ISSUE TITLE
portal not breaking correctly

### ISSUE THREAD

**Issue by mike112112** [xXastaspastaXx/Dimensions3#2]
when breaking portal the inside material stays as ghost

Could not pass event BlockBreakEvent to Dimensions v3.1.1-DEMO
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:160) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:154) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:293) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:252) ~[ProtocolLib.jar:?]
        at com.comphenix.packetwrapper.AbstractPacket.broadcastPacket(AbstractPacket.java:79) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.PortalEntitySand.destroyBroadcast(PortalEntitySand.java:114) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortal.destroy(CompletePortal.java:596) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortalManager.removePortal(CompletePortalManager.java:227) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:365) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:355) ~[Dimensions-DEMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor168.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1843]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:214) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1965) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1843]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xXastaspastaXx** [comment]
Can you please tell me what version is your minecraft server?
Also please make sure that you are using the latest version of ProtocolLib

**Comment by mike112112** [comment]
current purpur-1.19.2 build 1843
tested paper-1.19.2 build 265
latest protocollib build 602 https://ci.dmulloy2.net/job/ProtocolLib/602/

**Comment by mike112112** [comment]
same issue on both server forks

**Comment by mike112112** [comment]
on paper
[15:44:01 ERROR]: Could not pass event BlockBreakEvent to Dimensions v3.1.1-DEMO
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:160) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:181) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:154) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:293) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:252) ~[ProtocolLib.jar:?]
        at com.comphenix.packetwrapper.AbstractPacket.broadcastPacket(AbstractPacket.java:79) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.PortalEntitySand.destroyBroadcast(PortalEntitySand.java:114) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortal.destroy(CompletePortal.java:596) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortalManager.removePortal(CompletePortalManager.java:227) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:365) ~[Dimensions-DEMO.jar:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:355) ~[Dimensions-DEMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-271]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:214) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1883) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-271]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xXastaspastaXx** [comment]
Using the latest spigot build for 1.19.2, the plugin seems to be working fine.
The same error would pop while using older versions of ProtocolLib or after using the /reload command
Make sure you are using the latest build for protocolib by re-installing and also make sure you are using the latest build for paper
Unfortunately Dimensions is a spigot plugin and i wont be focusing on fixing problems that appear on paper builds.
If Dimensions keeps throwing this error even if you use spigot, please let me know

**Comment by mike112112** [comment]
spigot-1.19.2
[Server thread/ERROR]: Could not pass event BlockBreakEvent to Dimensions v3.1.1-DEMO
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:352) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:311) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:201) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1586) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:42) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3607-Spigot-6198b5a-e7aab54]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because "channel" is null
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.findInjector(NettyChannelInjector.java:160) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:103) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.sendServerPacket(NetworkManagerPlayerInjector.java:59) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:181) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:154) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:293) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:252) ~[?:?]
        at com.comphenix.packetwrapper.AbstractPacket.broadcastPacket(AbstractPacket.java:79) ~[?:?]
        at me.xxastaspastaxx.dimensions.completePortal.PortalEntitySand.destroyBroadcast(PortalEntitySand.java:114) ~[?:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortal.destroy(CompletePortal.java:596) ~[?:?]
        at me.xxastaspastaxx.dimensions.completePortal.CompletePortalManager.removePortal(CompletePortalManager.java:227) ~[?:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:365) ~[?:?]
        at me.xxastaspastaxx.dimensions.listener.PortalListener.onBlockChange(PortalListener.java:355) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by xXastaspastaXx** [comment]
I have been trying to find a solution for a few hours. But I can't understand what is the problem. And it could either be something wrong in the code or a few settings in your server, or even hardware.

The error is happening when the plugin tries to despawn the falling block entities inside the portal.

A temporary workaround until a solution has been found is to use NON-SOLID blocks, like water, lava, etc for the inside of the portal. (Nether portal is a NON-SOLID block but Dimensions will behave as if it is solid)

I will keep trying to figure out what's going wrong, but like I said, I have only seen this error in protocolLib when using the /reload command or when I use oldest versions of the plugin. If it is in fact ProtocolLib's fault, then you may want to seek help there as well. (Maybe they know what's wrong)
*(The reason I suspect it might be ProtocolLib or server settings is because I saw reports of the same error for 2 different plugins by the same person.)*
